-- MySQL Script generated by MySQL Workbench
-- Wed Apr 13 00:06:02 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema swp391
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `swp391` ;

-- -----------------------------------------------------
-- Schema swp391
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `swp391` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `swp391` ;

-- -----------------------------------------------------
-- Table `swp391`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swp391`.`roles` ;

CREATE TABLE IF NOT EXISTS `swp391`.`roles` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `swp391`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swp391`.`users` ;

CREATE TABLE IF NOT EXISTS `swp391`.`users` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `age` INT NOT NULL,
  `avatar` VARCHAR(255) NULL DEFAULT NULL,
  `birth_date` DATE NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `gender` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `password_token` VARCHAR(255) NULL DEFAULT NULL,
  `phone_number` VARCHAR(10) NOT NULL,
  `status` VARCHAR(255) NOT NULL,
  `role_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_6dotkott2kjsp8vw4d0m25fb7` (`email` ASC) VISIBLE,
  INDEX `FKp56c1712k691lhsyewcssf40f` (`role_id` ASC) VISIBLE,
  CONSTRAINT `FKp56c1712k691lhsyewcssf40f`
    FOREIGN KEY (`role_id`)
    REFERENCES `swp391`.`roles` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `swp391`.`company_information`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swp391`.`company_information` ;

CREATE TABLE IF NOT EXISTS `swp391`.`company_information` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `company_name` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(10) NOT NULL,
  `user_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKha6w76ta809d2ijx7ank68wv7` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FKha6w76ta809d2ijx7ank68wv7`
    FOREIGN KEY (`user_id`)
    REFERENCES `swp391`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `swp391`.`company_major`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swp391`.`company_major` ;

CREATE TABLE IF NOT EXISTS `swp391`.`company_major` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `salary` DOUBLE NULL DEFAULT NULL,
  `company_info_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKh8b709gag785o8i9oli3piwvj` (`company_info_id` ASC) VISIBLE,
  CONSTRAINT `FKh8b709gag785o8i9oli3piwvj`
    FOREIGN KEY (`company_info_id`)
    REFERENCES `swp391`.`company_information` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `swp391`.`cv`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swp391`.`cv` ;

CREATE TABLE IF NOT EXISTS `swp391`.`cv` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(255) NOT NULL,
  `experience` INT NOT NULL,
  `imageurl` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `swp391`.`skills`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swp391`.`skills` ;

CREATE TABLE IF NOT EXISTS `swp391`.`skills` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `swp391`.`cv_skill`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swp391`.`cv_skill` ;

CREATE TABLE IF NOT EXISTS `swp391`.`cv_skill` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `cv_id` BIGINT NOT NULL,
  `skill_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKpd8v26f7hxj1yqyq2t73u5i7j` (`cv_id` ASC) VISIBLE,
  INDEX `FKlb8rfdpwfk5p51c1m4wnturvd` (`skill_id` ASC) VISIBLE,
  CONSTRAINT `FKlb8rfdpwfk5p51c1m4wnturvd`
    FOREIGN KEY (`skill_id`)
    REFERENCES `swp391`.`skills` (`id`),
  CONSTRAINT `FKpd8v26f7hxj1yqyq2t73u5i7j`
    FOREIGN KEY (`cv_id`)
    REFERENCES `swp391`.`cv` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `swp391`.`majors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swp391`.`majors` ;

CREATE TABLE IF NOT EXISTS `swp391`.`majors` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `swp391`.`requests`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swp391`.`requests` ;

CREATE TABLE IF NOT EXISTS `swp391`.`requests` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `comment` VARCHAR(255) NULL DEFAULT NULL,
  `status` VARCHAR(255) NOT NULL,
  `from_id` BIGINT NOT NULL,
  `to_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK73f8tq09tanl448djuliwjqxa` (`from_id` ASC) VISIBLE,
  INDEX `FKfbb5tqrjhmml0skjp4naab7uy` (`to_id` ASC) VISIBLE,
  CONSTRAINT `FK73f8tq09tanl448djuliwjqxa`
    FOREIGN KEY (`from_id`)
    REFERENCES `swp391`.`users` (`id`),
  CONSTRAINT `FKfbb5tqrjhmml0skjp4naab7uy`
    FOREIGN KEY (`to_id`)
    REFERENCES `swp391`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `swp391`.`request_detail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swp391`.`request_detail` ;

CREATE TABLE IF NOT EXISTS `swp391`.`request_detail` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `major_id` BIGINT NOT NULL,
  `request_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKky1ydxjh4b5qvm8mrenwrcejp` (`major_id` ASC) VISIBLE,
  INDEX `FKg5943l8ytvhs1uiixluqmt91f` (`request_id` ASC) VISIBLE,
  CONSTRAINT `FKg5943l8ytvhs1uiixluqmt91f`
    FOREIGN KEY (`request_id`)
    REFERENCES `swp391`.`requests` (`id`),
  CONSTRAINT `FKky1ydxjh4b5qvm8mrenwrcejp`
    FOREIGN KEY (`major_id`)
    REFERENCES `swp391`.`majors` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `swp391`.`sample`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swp391`.`sample` ;

CREATE TABLE IF NOT EXISTS `swp391`.`sample` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
